### ISSUE TITLE
Working with background subtracted traces

### ISSUE THREAD

**Issue by 96ankithsharma** [JohnDieSchere/quickpbsa#3]
Hey John,

Thank you for uploading the code. 

I'm trying to use it to automate step detection on my traces that are already background subtracted. I don't have pixel coordinates for my traces, and comparing it with your examplestack_difference file my data starts from the 6th column. Reading your description of the code, it seems to me that I should be able to use this code directly on background-subtracted traces. My question is what should the format of the input .csv file look like if I don't have the pixel information?

I've tried removing all columns preceding the trace info from your examplestack_difference file, tried setting all pixel info values to 1, but it's not working (get an invalid syntax error). It runs partially though as I get kvout.csv and kvout.json files. 

Thanks for your help!

**Comment by JohnDieSchere** [comment]
Hi

Could you be more specific on what syntax error you get? And could you check what the kvout.csv file looks like, to help me understand if this part of the analysis works? In principle it sounds like the code should run with your input...

best wishes

**Comment by 96ankithsharma** [comment]
It's an invalid syntax <string> error (screenshot attached). 
![Screenshot (8)](https://user-images.githubusercontent.com/59638149/149180665-e0c19c47-96f5-49af-803c-f7e440ec94e9.png)

The kvout.csv file results are almost identical to what I get when I run using your original file (kv_time is slightly different but <1% difference). I've uploaded the kvout.csv and the input file (ExampleStack_difference2). 
[ExampleStack_difference2_kvout.csv](https://github.com/JohnDieSchere/quickpbsa/files/7856138/ExampleStack_difference2_kvout.csv)

[ExampleStack_difference2.csv](https://github.com/JohnDieSchere/quickpbsa/files/7856142/ExampleStack_difference2.csv)

Thanks!

**Comment by JohnDieSchere** [comment]
Hi

Have you tried running this code with my original example file? Because the syntax error is clearly not inside the package but in your code. Validating that this code runs with the provided examples would be the first step to find it I think.

**Comment by 96ankithsharma** [comment]
Hey, 

Yes, it runs with your example file... That is why I'm confused!! The only difference between the two are columns 2-6 in your example file that I set to 1 (file attached in my previous comment).

**Comment by 96ankithsharma** [comment]
Hey Johan, 

An update: When I copy your example file (which runs correctly) and paste it into another .csv file and try to run it, it's giving me the same error. So perhaps something is wrong with how it's reading the data from the input file?

**Comment by 96ankithsharma** [comment]
Final Update: Got it to work!! I switched to working from local directory and rectified the error. Thanks for the code, Johan.

**Comment by JohnDieSchere** [comment]
Great! Sorry I haven't been responsive, I had a very busy week and didn't
have the time to look into it properly. Good to know it works now.

96ankithsharma ***@***.***> schrieb am Do., 20. Jan. 2022,
16:19:
